language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower web-component-tester
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi
env:
  global:
  - secure: kIyBBurK61TDh0yK6rekAcP8Us2Wo5EQcGMYHpRt0S4hATnPWHLxm1IVhA0pePe/1ODX31kuBNkfxmX9uVTyOXLN1PynpUPTYAenmJB8MYB1AGU9MviQU5lCZ83glaPIcX3gK6q6JDQdKA2zkiAmh1x1Q7oBRSIA8avdCMhJ/w2BxCSegX+EpMyjd4USJXqTTckVvH581Jc1r+8wLqkVrizfD7vssSZuvvuhOck7623cljM89Is7vtLQP+/EmFGLnpx+wM9BbdhYyZHQ6Dw1nlXTW41nACYB6dqGPNDH8X9p+TcjBA/5QuAAMvX20vFsyYZp0zBAZaptOjV6uNR9ymWCqZWlx/GUw30t5pmsjdW3rfjKcMtbUOT7w1qF/OV2dDXHdtSJu+5/TBFW842AG6Bc2Vojt0qbJQR7ykqc+0FjD9X3J2BMwHaG9jgFyY/3wV2Og5AMI36W7wXOoxjR2+CGinFkQHhd5B9wjVKZQ0YbuxsfkzgYM5ku5FPsN7drCe7FycDQxC+AcmKIUHerAaWiJ1uqSwRgVKvu0qJ57uvdFJQDrwOTnCJRPMJOBgJw9A6zOfbzc7p0YFoYwwQ9MojHmn24AAqxcM/cXnh/qcJN+jfnhuFDKdhfNTz7tDtzniBpQwu/aMlqvLmkfhJGy/L17zx6VHv7JtKsnRbD0hw=
  - secure: B49yVdvuRzIwwOF6e3BuQifDjHuA/ScXoebM66lmqEIar/L00FOYUVOzaRtKqSRmUCRjhCD1JHzKJKLEcP1UuXoSm5IRSMna6ToAEtna5Ft6g8cMLI90qitlpZ3OYeKmLP/ziw092UGiQ+G0T+hCncO1LIGcEn5Ebti6F5jK45UwLbFp1Yq0JoYNx9RTbwNDDT7zT21oKj0mhLkn+squ+FXIp3BJ6krZeJLP2tnI4Z2Nk28FZ2K/YyxRF0+4sZsI8yWNByGUPYWk0v7nP/mrqbQepGsmMt+ae2LqkX5xefYbWGIlvDOJ7aWB/3qvdQu1m7BqIvfDIqYtwSca5DGWaJVEWdoreBOH8cYUd+dRs8pzliiUYqZlePd1Y3GvJMCxCKLcpqFIZhpXWbaV2K06qtBAAsNcc2z1a2RbNMUt0OTPOORMwB65Xw0WPJcRYN0fvOzYFxD8TNkyq9o+rV5f03uCFKBsK9G4exC99ILTo3/c6t2O8/eMz7mmRVBJlFFjd/c3O52DjbqWkI9svtu8Q7LI/8d07GvRImvkF9LHKRl82/ZcubCK3grUGv6bpxLunFAX9r16rnYBuv46OeBzZVPI1OwZTQssGpPT998ROKq+OK92BptBthAcYMGNw4TWM2vwbM9IRdy4aEDlCmP87ULajGZNbpq1yXOdtOM3gbM=
